events {}

http {
    resolver 127.0.0.11 valid=30s;

    upstream app_backend_hashed {
        zone shared_zone 64k;
        hash $cookie_StickyStr consistent;
        server app1:8000 max_fails=3 fail_timeout=1h resolve;
        server app2:8000 max_fails=3 fail_timeout=1h resolve;
        server app3:8000 max_fails=3 fail_timeout=1h resolve;
    }

    upstream app_backend_rr {
        zone shared_zone 64k;
        server app1:8000 max_fails=3 fail_timeout=1h resolve;
        server app2:8000 max_fails=3 fail_timeout=1h resolve;
        server app3:8000 max_fails=3 fail_timeout=1h resolve;
    }

    map $cookie_StickyStr $use_hashed_backend {
        default app_backend_hashed;
        ""      app_backend_rr;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$use_hashed_backend;

            proxy_next_upstream error timeout http_502 http_503 http_504;
            error_page 502 503 504 = @fallback;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffering off;
        }

        location @fallback {
            root /usr/share/nginx/html;
            index fallback.html;
        }
    }
}
